# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nitishsharma/test-branch1

pool:
  vmImage: macOS-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.7'
- task: Bash@3
  inputs:
    filePath: 'test-build.sh'
